global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'bank-service'
    static_configs:
      - targets: ['bank-service:8080']
    metrics_path: '/metrics'

  - job_name: 'exchange-service'
    static_configs:
      - targets: ['exchange-service:8086']
    metrics_path: '/metrics'

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:8082']
    metrics_path: '/metrics'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8083']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

